#!/bin/sh
APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="${APPDIR}/usr/bin:${APPDIR}/qtile/bin:${PATH}"

if [ ! -d ~/.config/qtile ]; then
    cp -r ${APPDIR}/config ~/.config/qtile
fi

unset PYTHONPATH
unset PYTHONHOME
unset PYTHONLIBRARY
export PYTHONPATH="${APPDIR}/qtile"
export PYTHONHOME="${APPDIR}/usr"
export PYTHONLIBRARY="${APPDIR}/usr/lib/python3.10"
export PYTHONNOUSERSITE=1
while true; do
    exec "${APPDIR}/usr/bin/python" "${APPDIR}/qtile/bin/qtile" "$@"
done

