#!/bin/sh
APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="${APPDIR}/usr/bin:${APPDIR}/qtile/bin:${PATH}"

if [ ! -d ~/.config/qtile ]; then
    cp -r ${APPDIR}/config ~/.config/qtile
fi

export PYTHONPATH="${APPDIR}/qtile:${PYTHONPATH}"

while true; do
    exec "${APPDIR}/qtile/bin/qtile" "$@"
done
